
import __ASTRO_IMAGE_IMPORT_1txwhp from "@/assets/images/people/andy-schoen.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fpeople%2Fandy-schoen.mdx";
import __ASTRO_IMAGE_IMPORT_ZHscHC from "@/assets/images/hardware/jibo-hero.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fhardware%2Fjibo.mdx";
import __ASTRO_IMAGE_IMPORT_NcEwd from "@/assets/images/hardware/ommie-hero.png?astroContentImageFlag=&importer=src%2Fcontent%2Fhardware%2Fommie.mdx";
import __ASTRO_IMAGE_IMPORT_ZnP4Hf from "@/assets/images/hardware/quori.v1-hero.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fhardware%2Fquori.v1.mdx";
import __ASTRO_IMAGE_IMPORT_yfVDn from "@/assets/images/hardware/quori.v2-hero.png?astroContentImageFlag=&importer=src%2Fcontent%2Fhardware%2Fquori.v2.mdx";
import __ASTRO_IMAGE_IMPORT_Z2r3lvU from "@/assets/images/software/arora-hero.png?astroContentImageFlag=&importer=src%2Fcontent%2Fsoftware%2Farora.mdx";
import __ASTRO_IMAGE_IMPORT_eSpzA from "@/assets/images/people/chris-birmingham.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fpeople%2Fchris-birmingham.mdx";
import __ASTRO_IMAGE_IMPORT_5gaxF from "@/assets/images/people/ross-mead.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fpeople%2Fross-mead.mdx";
import __ASTRO_IMAGE_IMPORT_1F1Inp from "@/assets/images/people/saad-elbeleidy.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fpeople%2Fsaad-elbeleidy.mdx";
export default new Map([["@/assets/images/people/andy-schoen.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fpeople%2Fandy-schoen.mdx", __ASTRO_IMAGE_IMPORT_1txwhp], ["@/assets/images/hardware/jibo-hero.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fhardware%2Fjibo.mdx", __ASTRO_IMAGE_IMPORT_ZHscHC], ["@/assets/images/hardware/ommie-hero.png?astroContentImageFlag=&importer=src%2Fcontent%2Fhardware%2Fommie.mdx", __ASTRO_IMAGE_IMPORT_NcEwd], ["@/assets/images/hardware/quori.v1-hero.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fhardware%2Fquori.v1.mdx", __ASTRO_IMAGE_IMPORT_ZnP4Hf], ["@/assets/images/hardware/quori.v2-hero.png?astroContentImageFlag=&importer=src%2Fcontent%2Fhardware%2Fquori.v2.mdx", __ASTRO_IMAGE_IMPORT_yfVDn], ["@/assets/images/software/arora-hero.png?astroContentImageFlag=&importer=src%2Fcontent%2Fsoftware%2Farora.mdx", __ASTRO_IMAGE_IMPORT_Z2r3lvU], ["@/assets/images/people/chris-birmingham.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fpeople%2Fchris-birmingham.mdx", __ASTRO_IMAGE_IMPORT_eSpzA], ["@/assets/images/people/ross-mead.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fpeople%2Fross-mead.mdx", __ASTRO_IMAGE_IMPORT_5gaxF], ["@/assets/images/people/saad-elbeleidy.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fpeople%2Fsaad-elbeleidy.mdx", __ASTRO_IMAGE_IMPORT_1F1Inp]]);
		